// ── Helpers ──────────────────────────────────────────────────────────────────

function list(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return 'None';
  return arr.join(', ');
}

function bullet(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return '';
  return arr.map((i) => `- ${i}`).join('\n');
}

function yesNo(val) {
  return val ? 'Yes' : 'No';
}

function formatDate(iso) {
  return new Date(iso).toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

// ── Section builders ─────────────────────────────────────────────────────────

function buildOverview({ projectName, projectType, language, description, generatedAt }) {
  return [
    `# Project Spec: ${projectName}`,
    '',
    `> **Generated by Accelerator Enterprise Architecture Compiler** on ${formatDate(generatedAt)}`,
    '> Paste this file into Claude Code, Codex, or Cursor and let it scaffold the full repository.',
    '',
    '---',
    '',
    '## 1. Overview',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Project Name** | \`${projectName}\` |`,
    `| **Type** | \`${projectType}\` |`,
    `| **Primary Language** | \`${language}\` |`,
    `| **Description** | *${description}* |`,
    '',
    '---',
    '',
  ].join('\n');
}

function buildFrontend({ frontend }) {
  if (!frontend.hasFrontend) return '## 2. Frontend\n_No frontend included._\n\n---\n\n';

  const apiUrlVar = frontend.framework.includes('Vite') ? 'VITE_API_URL'
    : frontend.framework.includes('Nuxt') ? 'NUXT_PUBLIC_API_URL'
    : frontend.framework.includes('Svelte') ? 'PUBLIC_API_URL'
    : 'NEXT_PUBLIC_API_URL';

  const extrasBlock = frontend.frontendExtras.length > 0
    ? `\n### Additional Tooling\n${bullet(frontend.frontendExtras)}\n` : '';

  return [
    '## 2. Frontend',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Framework** | \`${frontend.framework}\` |`,
    `| **Styling** | \`${frontend.styling}\` |`,
    `| **State Management** | \`${frontend.stateManagement}\` |`,
    `| **Data Fetching** | \`${frontend.dataFetching}\` |`,
    `| **Form Handling** | \`${frontend.formHandling}\` |`,
    extrasBlock,
    '### Required Environment Variables',
    '',
    '```env',
    '# frontend/.env.local',
    `${apiUrlVar}=http://localhost:8000/api`,
    '```',
    '',
    '> **SSR Note** (Next.js / Nuxt / SvelteKit): server-side fetches inside Docker must use the backend service name,',
    '> e.g. `http://backend:8000/api`. Client-side fetches always use `localhost`.',
    '',
    '### Design System Adapter Bindings',
    '- Read colors, spacing, and typography from `shared_tokens.md` before writing any CSS.',
    '- **W-4 FIX**: Convert HEX values in `shared_tokens.md` to CSS HSL fragments so Tailwind maps correctly.',
    '- Implement a `data-theme` dark/light toggle wired to the token system.',
    '',
    '---',
    '',
  ].join('\n');
}

function buildBackend({ backend }) {
  if (!backend.hasBackend) return '## 3. Backend\n_No backend included._\n\n---\n\n';

  const extrasBlock = backend.backendExtras.length > 0
    ? `\n### Features Enabled\n${bullet(backend.backendExtras)}\n` : '';

  const structureHint = backend.framework === 'NestJS'
    ? 'backend/src/{module}/{module}.controller.ts, .service.ts, .module.ts'
    : backend.framework === 'Django'
    ? 'backend/apps/{app}/views.py, models.py, serializers.py, urls.py'
    : backend.framework === 'FastAPI'
    ? 'backend/app/routers/{resource}.py, schemas/{resource}.py, models/{resource}.py'
    : 'backend/src/routes/{resource}.ts, controllers/{resource}.ts, services/{resource}.ts';

  return [
    '## 3. Backend',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Framework** | \`${backend.framework}\` |`,
    `| **API Style** | \`${backend.apiStyle}\` |`,
    `| **Validation** | \`${backend.validation}\` |`,
    extrasBlock,
    '### Required Environment Variables',
    '',
    '```env',
    '# backend/.env',
    'DATABASE_URL=postgresql://postgres:postgres@localhost:5432/appdb',
    'JWT_SECRET=change-me-in-production',
    'PORT=8000',
    '```',
    '',
    '### Module Pattern',
    '```',
    structureHint,
    'backend/src/common/          # shared guards, filters, interceptors, pipes',
    'backend/src/config/          # environment config module',
    '```',
    '',
    '### Health Endpoint (L-2 Rule)',
    '- Route: `GET /api/health` → `{ status: "ok" }` with HTTP 200',
    '- **Verify this returns 200 before writing a single frontend component.**',
    '',
    '---',
    '',
  ].join('\n');
}

function buildDatabase({ database }) {
  if (!database.hasDatabase) return '## 4. Database\n_No database included._\n\n---\n\n';

  const hasSQLite = database.databases.includes('SQLite');
  const hasPostgres = database.databases.some((d) =>
    ['PostgreSQL', 'MySQL', 'PlanetScale', 'Supabase'].includes(d));
  const hasMongo = database.databases.includes('MongoDB');

  let connFix = '- Use the standard connection URL format for your database driver.';
  if (database.orm === 'Prisma')
    connFix = '- **C-2 FIX**: Use `postgresql://` (not `postgres://`) in `DATABASE_URL` — Prisma rejects the shorter prefix.';
  else if (database.orm === 'SQLAlchemy')
    connFix = '- Use `postgresql+asyncpg://` for async SQLAlchemy, `postgresql://` for sync.';
  else if (database.orm === 'Django ORM')
    connFix = '- Configure via `dj-database-url` or the `DATABASES` dict in `settings.py`.';
  else if (database.orm === 'TypeORM')
    connFix = '- Use `type: "postgres"` in `DataSource` config; set `synchronize: false` in production.';
  else if (database.orm === 'Drizzle ORM')
    connFix = '- Use `drizzle-kit push` for dev, `drizzle-kit generate` + `migrate` for production.';

  const migrationCmd = database.orm === 'Prisma'
    ? '`npx prisma migrate dev` (dev) / `npx prisma migrate deploy` (prod)'
    : database.orm === 'Drizzle ORM'
    ? '`npx drizzle-kit push` (dev) / `npx drizzle-kit generate` then migrate (prod)'
    : database.orm === 'TypeORM'
    ? '`npm run typeorm migration:run`'
    : database.orm === 'Django ORM'
    ? '`python manage.py makemigrations && python manage.py migrate`'
    : database.orm === 'SQLAlchemy'
    ? '`alembic upgrade head`'
    : '_No ORM migration tool — manage manually_';

  const dbImage = hasMongo ? 'mongo:7' : 'postgres:16-alpine';
  const dbEnv = hasPostgres
    ? 'POSTGRES_DB: appdb\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: postgres'
    : 'MONGO_INITDB_DATABASE: appdb';
  const dbPort = hasMongo ? '27017:27017' : '5432:5432';

  return [
    '## 4. Database',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Databases** | \`${list(database.databases)}\` |`,
    `| **ORM / Query Layer** | \`${database.orm}\` |`,
    `| **Migrations** | \`${yesNo(database.hasMigrations)}\` |`,
    `| **Seed Scripts** | \`${yesNo(database.hasSeed)}\` |`,
    '',
    '### Connection Rules',
    connFix,
    hasSQLite ? '- **SQLite**: use `file:./dev.db` (dev) or `file:/app/db/local.db` (Docker). Skip the Postgres container.' : '',
    hasPostgres ? '- In Docker, the DB host is the service name (e.g. `db`), not `localhost`.' : '',
    hasMongo ? '- MongoDB URI: `mongodb://user:pass@db:27017/dbname` inside Docker.' : '',
    '',
    '### Migration Commands',
    `- Run: ${migrationCmd}`,
    database.hasSeed ? '- Run seed scripts immediately after migrations.' : '',
    '',
    '### Docker Compose DB Reference',
    '```yaml',
    'services:',
    '  db:',
    `    image: ${dbImage}`,
    '    environment:',
    `      ${dbEnv}`,
    '    ports:',
    `      - "${dbPort}"`,
    '```',
    '',
    '---',
    '',
  ].filter((l) => l !== false).join('\n');
}

function buildAuth({ auth, projectType }) {
  if (projectType === 'frontend')
    return '## 5. Authentication & Authorization\n_Not applicable — frontend-only project._\n\n---\n\n';
  if (!auth.hasAuth)
    return '## 5. Authentication & Authorization\n_No authentication included._\n\n---\n\n';

  const oauthVars = [
    auth.authMethods.includes('Google OAuth') ? 'GOOGLE_CLIENT_ID=\nGOOGLE_CLIENT_SECRET=' : '',
    auth.authMethods.includes('Azure AD OAuth') ? 'AZURE_AD_TENANT_ID=\nAZURE_AD_CLIENT_ID=\nAZURE_AD_CLIENT_SECRET=' : '',
    auth.authMethods.includes('GitHub OAuth') ? 'GITHUB_CLIENT_ID=\nGITHUB_CLIENT_SECRET=' : '',
  ].filter(Boolean).join('\n');

  const rolesBlock = auth.hasRBAC && auth.roles.length > 0
    ? `\n### Roles (RBAC)\nDefine and enforce these roles via guards/middleware:\n${bullet(auth.roles)}\n` : '';

  return [
    '## 5. Authentication & Authorization',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Strategy** | \`${auth.authStrategy}\` |`,
    `| **Implementation** | \`${auth.authProvider}\` |`,
    `| **RBAC** | \`${yesNo(auth.hasRBAC)}\` |`,
    `| **Multi-Tenant** | \`${yesNo(auth.hasMultiTenant)}\` |`,
    '',
    '### Auth Methods',
    bullet(auth.authMethods),
    '',
    '### Required Environment Variables',
    '',
    '```env',
    '# backend/.env',
    'JWT_SECRET=change-me-in-production',
    'JWT_EXPIRES_IN=7d',
    oauthVars,
    '# frontend/.env.local',
    'NEXTAUTH_SECRET=change-me-in-production',
    'NEXTAUTH_URL=http://localhost:3000',
    '```',
    '',
    '### Implementation Rules',
    '- Protect all non-public routes with auth guards/middleware.',
    '- Store tokens in HTTP-only cookies — never in localStorage.',
    '- Refresh tokens must be rotated on every use.',
    auth.hasMultiTenant ? '- Multi-tenant: scope every DB query to the resolved `tenantId`. Cross-tenant access is a critical security bug.' : '',
    rolesBlock,
    '---',
    '',
  ].filter((l) => l !== false).join('\n');
}

function buildInfra({ infra }) {
  const parts = [
    '## 6. Infrastructure & DevOps',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Cloud / Platform** | \`${infra.cloud}\` |`,
    `| **Terraform (IaC)** | \`${yesNo(infra.hasTerraform)}\` |`,
    `| **Docker** | \`${yesNo(infra.hasDocker)}\` |`,
    `| **CI/CD** | \`${infra.hasCICD ? `Yes — ${infra.cicdPlatform}` : 'No'}\` |`,
    '',
  ];

  if (infra.hasDocker) {
    if (infra.dockerFeatures.length > 0) {
      parts.push('### Docker Setup');
      parts.push(bullet(infra.dockerFeatures));
      parts.push('');
    }
    parts.push('### Docker Port Rules (C-1 — mandatory)');
    parts.push('- Frontend: `EXPOSE 3000` — process must listen on port 3000');
    parts.push('- Backend: `EXPOSE 8000` — process must listen on port 8000');
    parts.push('- Use service names (`backend`, `db`) for inter-container communication, never `localhost`');
    parts.push('- Add `depends_on: { db: { condition: service_healthy } }` to avoid race conditions');
    parts.push('');
  }

  if (infra.hasCICD && infra.cicdSteps.length > 0) {
    parts.push(`### CI/CD Pipeline (${infra.cicdPlatform})`);
    parts.push(bullet(infra.cicdSteps));
    parts.push('');
  }

  if (infra.codeQuality.length > 0) {
    parts.push('### Code Quality Tools');
    parts.push(bullet(infra.codeQuality));
    parts.push('');
    const notes = [
      infra.codeQuality.includes('ESLint') && '- **ESLint**: `eslint.config.mjs` (flat config). Use `@typescript-eslint/recommended` + framework plugin.',
      infra.codeQuality.includes('Prettier') && '- **Prettier**: `.prettierrc` → `{ "singleQuote": true, "semi": true, "printWidth": 100 }`.',
      infra.codeQuality.includes('Husky') && '- **Husky**: `npx husky init` → add pre-commit hook to run lint-staged.',
      infra.codeQuality.includes('lint-staged') && '- **lint-staged**: in `package.json` → run ESLint + Prettier on staged `*.ts` / `*.tsx` files.',
      infra.codeQuality.includes('Commitlint') && '- **Commitlint**: `@commitlint/config-conventional` + commit-msg Husky hook.',
      infra.codeQuality.includes('SonarQube') && '- **SonarQube**: `sonar-project.properties` at root. Set `sonar.sources`, `sonar.tests`, coverage exclusions.',
    ].filter(Boolean);
    if (notes.length > 0) parts.push(...notes, '');
  }

  if (infra.infraExtras.length > 0) {
    parts.push('### Additional Infrastructure');
    parts.push(bullet(infra.infraExtras));
    parts.push('');
  }

  if (infra.hasTerraform) {
    parts.push('### Terraform');
    parts.push(`- Provider: \`${infra.cloud}\``);
    parts.push('- Modules in `terraform/`: networking, compute, database, IAM');
    parts.push('- Use remote state backend (S3 / Azure Blob / GCS)');
    parts.push('');
  }

  parts.push('---', '');
  return parts.join('\n');
}

function buildQuality({ quality }) {
  if (quality.testingFramework === 'None')
    return '## 7. Testing & Quality Assurance\n_No testing framework selected._\n\n---\n\n';

  const testTypesBlock = quality.testTypes.length > 0
    ? `\n### Test Types\n${bullet(quality.testTypes)}\n` : '';

  const coverageBlock = quality.hasCoverage
    ? '\n### Coverage Thresholds\nMinimum 80% for lines, functions, and branches. Fail CI if not met.\n' : '';

  return [
    '## 7. Testing & Quality Assurance',
    '',
    '| Field | Value |',
    '|:---|:---|',
    `| **Testing Framework** | \`${quality.testingFramework}\` |`,
    `| **Coverage Enforced** | \`${yesNo(quality.hasCoverage)}\` |`,
    testTypesBlock,
    coverageBlock,
    '---',
    '',
  ].join('\n');
}

// ── Directory tree builder ────────────────────────────────────────────────────

function buildBackendTreeLines(backend, database, auth, infra, language) {
  const L = [];
  if (!backend.hasBackend) return L;

  L.push('├── backend/');

  if (['NestJS', 'Express.js', 'Fastify', 'Hono'].includes(backend.framework)) {
    L.push('│   ├── src/');
    L.push('│   │   ├── main.ts');
    L.push('│   │   ├── app.module.ts');
    L.push('│   │   ├── common/');
    L.push('│   │   │   ├── guards/');
    L.push('│   │   │   ├── filters/');
    L.push('│   │   │   ├── interceptors/');
    L.push('│   │   │   └── pipes/');
    L.push('│   │   ├── config/');
    L.push('│   │   │   └── configuration.ts');
    L.push('│   │   ├── health/');
    L.push('│   │   │   ├── health.controller.ts');
    L.push('│   │   │   └── health.module.ts');
    if (auth.hasAuth) {
      L.push('│   │   ├── auth/');
      L.push('│   │   │   ├── auth.controller.ts');
      L.push('│   │   │   ├── auth.service.ts');
      L.push('│   │   │   ├── auth.module.ts');
      L.push('│   │   │   ├── dto/');
      L.push('│   │   │   └── strategies/');
      L.push('│   │   │       └── jwt.strategy.ts');
    }
    L.push('│   │   └── users/');
    L.push('│   │       ├── users.controller.ts');
    L.push('│   │       ├── users.service.ts');
    L.push('│   │       ├── users.module.ts');
    L.push('│   │       └── dto/');
  } else if (backend.framework === 'FastAPI') {
    L.push('│   ├── app/');
    L.push('│   │   ├── main.py');
    L.push('│   │   ├── core/');
    L.push('│   │   │   ├── config.py');
    L.push('│   │   │   └── security.py');
    L.push('│   │   ├── routers/');
    L.push('│   │   │   ├── health.py');
    if (auth.hasAuth) L.push('│   │   │   ├── auth.py');
    L.push('│   │   │   └── users.py');
    L.push('│   │   ├── schemas/');
    L.push('│   │   ├── models/');
    if (database.hasDatabase) {
      L.push('│   │   └── db/');
      L.push('│   │       ├── session.py');
      L.push('│   │       └── base.py');
    }
  } else if (backend.framework === 'Django') {
    L.push('│   ├── config/');
    L.push('│   │   ├── settings/');
    L.push('│   │   │   ├── base.py');
    L.push('│   │   │   ├── development.py');
    L.push('│   │   │   └── production.py');
    L.push('│   │   ├── urls.py');
    L.push('│   │   └── wsgi.py');
    L.push('│   ├── apps/');
    L.push('│   │   ├── health/');
    L.push('│   │   │   ├── views.py');
    L.push('│   │   │   └── urls.py');
    if (auth.hasAuth) {
      L.push('│   │   ├── accounts/');
      L.push('│   │   │   ├── models.py');
      L.push('│   │   │   ├── views.py');
      L.push('│   │   │   ├── serializers.py');
      L.push('│   │   │   └── urls.py');
    }
    L.push('│   │   └── users/');
    L.push('│   │       ├── models.py');
    L.push('│   │       ├── views.py');
    L.push('│   │       ├── serializers.py');
    L.push('│   │       └── urls.py');
    L.push('│   └── manage.py');
  }

  // ORM / migration files
  if (database.hasDatabase) {
    if (database.orm === 'Prisma') {
      L.push('│   ├── prisma/');
      L.push('│   │   ├── schema.prisma');
      L.push('│   │   └── migrations/');
      if (database.hasSeed) L.push('│   │   └── seed.ts');
    } else if (database.orm === 'Drizzle ORM') {
      L.push('│   ├── drizzle/');
      L.push('│   │   ├── schema.ts');
      L.push('│   │   └── migrations/');
    } else if (database.orm === 'SQLAlchemy' || database.orm === 'Tortoise ORM') {
      L.push('│   ├── alembic/');
      L.push('│   │   ├── env.py');
      L.push('│   │   └── versions/');
    } else if (database.orm === 'TypeORM') {
      L.push('│   ├── migrations/');
    }
  }

  L.push('│   ├── test/');
  L.push('│   ├── .env.example');

  if (language === 'Python') {
    L.push('│   ├── requirements.txt');
    L.push('│   ├── pyproject.toml');
  } else {
    L.push('│   ├── package.json');
    L.push('│   ├── tsconfig.json');
  }

  if (infra.hasDocker) L.push('│   └── Dockerfile');

  return L;
}

function buildFrontendTreeLines(frontend, auth, infra) {
  const L = [];
  if (!frontend.hasFrontend) return L;

  // frontend is always last — use └── at root
  L.push('└── frontend/');

  if (frontend.framework === 'Next.js') {
    L.push('    ├── app/');
    L.push('    │   ├── layout.tsx');
    L.push('    │   ├── page.tsx');
    L.push('    │   ├── globals.css');
    if (auth.hasAuth) {
      L.push('    │   ├── (auth)/');
      L.push('    │   │   ├── login/');
      L.push('    │   │   │   └── page.tsx');
      L.push('    │   │   └── register/');
      L.push('    │   │       └── page.tsx');
    }
    L.push('    │   └── (dashboard)/');
    L.push('    │       ├── layout.tsx');
    L.push('    │       └── page.tsx');
    L.push('    ├── components/');
    L.push('    │   ├── ui/');
    L.push('    │   ├── layouts/');
    L.push('    │   └── forms/');
    L.push('    ├── lib/');
    L.push('    │   ├── api.ts');
    L.push('    │   └── utils.ts');
    L.push('    ├── hooks/');
    if (['Zustand', 'Redux Toolkit', 'Jotai'].includes(frontend.stateManagement)) {
      L.push('    ├── store/');
    }
    L.push('    ├── types/');
    L.push('    ├── public/');
    L.push('    ├── .env.local.example');
    L.push('    ├── next.config.ts');
    L.push('    ├── tsconfig.json');
    if (frontend.styling.includes('Tailwind')) L.push('    ├── tailwind.config.ts');
  } else if (frontend.framework === 'React + Vite') {
    L.push('    ├── src/');
    L.push('    │   ├── main.tsx');
    L.push('    │   ├── App.tsx');
    L.push('    │   ├── components/');
    L.push('    │   │   ├── ui/');
    L.push('    │   │   └── layouts/');
    if (auth.hasAuth) L.push('    │   ├── features/');
    L.push('    │   ├── pages/');
    L.push('    │   ├── hooks/');
    L.push('    │   ├── lib/');
    L.push('    │   │   └── api.ts');
    if (frontend.stateManagement !== 'None') L.push('    │   ├── store/');
    L.push('    │   ├── types/');
    L.push('    │   └── styles/');
    L.push('    ├── public/');
    L.push('    ├── .env.example');
    L.push('    ├── vite.config.ts');
    L.push('    ├── tsconfig.json');
    if (frontend.styling.includes('Tailwind')) L.push('    ├── tailwind.config.ts');
  } else if (frontend.framework === 'Nuxt 3') {
    L.push('    ├── pages/');
    L.push('    │   ├── index.vue');
    if (auth.hasAuth) L.push('    │   ├── login.vue');
    L.push('    │   └── dashboard.vue');
    L.push('    ├── components/');
    L.push('    ├── composables/');
    L.push('    ├── server/');
    L.push('    │   └── api/');
    L.push('    ├── stores/');
    L.push('    ├── layouts/');
    L.push('    ├── assets/');
    L.push('    │   └── css/');
    L.push('    ├── public/');
    L.push('    ├── .env.example');
    L.push('    ├── nuxt.config.ts');
    L.push('    └── tsconfig.json');
  } else if (frontend.framework === 'SvelteKit') {
    L.push('    ├── src/');
    L.push('    │   ├── app.html');
    L.push('    │   ├── app.css');
    L.push('    │   ├── lib/');
    L.push('    │   │   ├── components/');
    L.push('    │   │   ├── server/');
    L.push('    │   │   └── utils.ts');
    L.push('    │   └── routes/');
    L.push('    │       ├── +layout.svelte');
    L.push('    │       ├── +page.svelte');
    if (auth.hasAuth) {
      L.push('    │       ├── login/');
      L.push('    │       │   └── +page.svelte');
    }
    L.push('    │       └── dashboard/');
    L.push('    │           ├── +page.svelte');
    L.push('    │           └── +page.server.ts');
    L.push('    ├── static/');
    L.push('    ├── .env.example');
    L.push('    ├── svelte.config.js');
    L.push('    ├── vite.config.ts');
    L.push('    └── tsconfig.json');
  }

  if (infra.hasDocker) L.push('    └── Dockerfile');

  return L;
}

function buildDirectoryTree(answers) {
  const {
    projectName = 'my-project',
    projectType,
    language = 'TypeScript',
    frontend,
    backend,
    database,
    auth,
    infra,
  } = answers;

  const slug = projectName.toLowerCase().replace(/\s+/g, '-');
  const L = [];

  L.push('```text');
  L.push(`${slug}/`);

  // Root config
  L.push('├── CLAUDE.md');
  L.push('├── SPEC.md');
  L.push('├── shared_tokens.md');
  L.push('├── .env.example');
  L.push('├── .gitignore');
  L.push('├── README.md');

  // Code quality root configs
  if (infra.codeQuality.includes('ESLint'))       L.push('├── eslint.config.mjs');
  if (infra.codeQuality.includes('Prettier'))     L.push('├── .prettierrc');
  if (infra.codeQuality.includes('EditorConfig')) L.push('├── .editorconfig');
  if (infra.codeQuality.includes('Commitlint'))   L.push('├── commitlint.config.js');
  if (infra.codeQuality.includes('Husky')) {
    L.push('├── .husky/');
    L.push('│   └── pre-commit');
  }

  // Assets
  L.push('├── assets/');
  L.push('│   ├── logo.svg');
  L.push('│   ├── logo-mark.svg');
  L.push('│   ├── favicon.ico');
  L.push('│   └── fonts/');

  // Docker compose
  if (infra.hasDocker) L.push('├── docker-compose.yml');

  // CI/CD
  if (infra.hasCICD) {
    if (infra.cicdPlatform === 'GitHub Actions') {
      L.push('├── .github/');
      L.push('│   └── workflows/');
      L.push('│       └── ci.yml');
    } else if (infra.cicdPlatform === 'GitLab CI') {
      L.push('├── .gitlab-ci.yml');
    } else if (infra.cicdPlatform === 'CircleCI') {
      L.push('├── .circleci/');
      L.push('│   └── config.yml');
    } else {
      L.push(`├── .${infra.cicdPlatform.toLowerCase().replace(/\s+/g, '-')}-ci.yml`);
    }
  }

  // Terraform
  if (infra.hasTerraform) {
    L.push('├── terraform/');
    L.push('│   ├── main.tf');
    L.push('│   ├── variables.tf');
    L.push('│   ├── outputs.tf');
    L.push('│   └── modules/');
  }

  // Backend + Frontend (frontend always last with └──)
  L.push(...buildBackendTreeLines(backend, database, auth, infra, language));
  L.push(...buildFrontendTreeLines(frontend, auth, infra));

  L.push('```');

  return [
    '## 9. Project Directory Structure',
    '',
    'The agent **must** scaffold the repository using exactly this folder layout.',
    'Do not invent directories or deviate from this structure without explicit instruction.',
    '',
    L.join('\n'),
    '',
    '> Directory and file names with `{resource}` or `{module}` are placeholders.',
    '> Replace them with actual domain entity names (e.g. `products/`, `orders/`).',
    '',
    '---',
    '',
  ].join('\n');
}

// ── Scaffold instructions (now section 10) ────────────────────────────────────

function buildScaffoldInstructions(answers) {
  const { frontend, backend, database, auth, infra, quality } = answers;

  return [
    '## 10. AI Scaffold Instructions',
    '',
    'You are an expert full-stack systems engineering agent.',
    'Read `CLAUDE.md`, `SPEC.md`, and `shared_tokens.md` **completely** before writing a single line of code.',
    'Scaffold the repository following this pipeline exactly — do not skip steps or reorder them.',
    '',
    '### Pipeline',
    '',
    '1. **Root Foundations**',
    '   - Create `.gitignore`, `README.md`, root `package.json` / `pyproject.toml`.',
    '   - Generate `backend/.env.example` and `frontend/.env.local.example` with all variables from Sections 3 and 5.',
    infra.codeQuality.length > 0 ? `   - Configure code quality tools: ${list(infra.codeQuality)}.` : '',
    '',
    `2. **Database Schema** *(${database.hasDatabase ? `${list(database.databases)} via ${database.orm}` : 'skipped — no database'})*`,
    database.hasDatabase
      ? `   - Write schema / model files.\n   - Generate initial migration.\n   ${database.hasSeed ? '- Write deterministic seed scripts.' : ''}`
      : '   _Skipped._',
    '',
    `3. **Core Backend — L-2 Rule** *(${backend.hasBackend ? backend.framework : 'skipped'})*`,
    backend.hasBackend
      ? `   - Scaffold app bootstrap, module structure, shared middleware.\n   - Implement \`GET /api/health\` → \`{ status: "ok" }\`.\n   - **⛔ Do not write frontend code until \`curl http://localhost:8000/api/health\` returns HTTP 200.**`
      : '   _Skipped._',
    '',
    `4. **Auth Layer** *(${auth.hasAuth ? `${auth.authProvider} — ${list(auth.authMethods)}` : 'skipped'})*`,
    auth.hasAuth
      ? `   - Wire up ${auth.authProvider} with: ${list(auth.authMethods)}.\n   - Apply auth guards to all non-public routes.\n   ${auth.hasRBAC ? `- Implement RBAC guards for roles: ${list(auth.roles)}.` : ''}`
      : '   _Skipped._',
    '',
    `5. **Frontend Scaffold** *(${frontend.hasFrontend ? frontend.framework : 'skipped'})*`,
    frontend.hasFrontend
      ? `   - Bootstrap with non-interactive CLI flags.\n   - Apply design tokens from \`shared_tokens.md\` — convert HEX → HSL.\n   - Implement dark/light theme toggle via \`data-theme\`.\n   - Dashboard shell with live connection indicator calling \`/api/health\`.`
      : '   _Skipped._',
    '',
    `6. **Docker Orchestration** *(${infra.hasDocker ? 'enabled' : 'skipped'})*`,
    infra.hasDocker
      ? `   - Multi-stage Dockerfiles: frontend \`EXPOSE 3000\`, backend \`EXPOSE 8000\`.\n   - \`docker-compose.yml\`: all services wired with healthchecks and service-name references.`
      : '   _Skipped._',
    '',
    `7. **CI/CD** *(${infra.hasCICD ? `${infra.cicdPlatform} — ${list(infra.cicdSteps)}` : 'skipped'})*`,
    infra.hasCICD ? `   - Generate pipeline config running: ${list(infra.cicdSteps)}.` : '   _Skipped._',
    '',
    `8. **Tests** *(${quality.testingFramework !== 'None' ? `${quality.testingFramework} — ${list(quality.testTypes)}` : 'skipped'})*`,
    quality.testingFramework !== 'None'
      ? `   - Scaffold test files alongside source files.\n   ${quality.hasCoverage ? '- Enforce 80% coverage thresholds in CI.' : ''}`
      : '   _Skipped._',
    '',
    '9. **README.md**',
    '   - Local setup: clone → install → env setup → migrate → run',
    '   - All environment variables documented',
    '   - How to run tests and Docker',
    '',
    '### Critical Rules',
    '- Never hardcode secrets — use environment variables exclusively.',
    '- Never use `localhost` as a hostname inside Docker containers — use service names.',
    '- Follow the L-2 rule: backend `/health` endpoint verified before any frontend code is written.',
    '- Follow Section 9 directory structure exactly.',
  ].filter((l) => l !== false).join('\n');
}

// ── Main renderer ─────────────────────────────────────────────────────────────

export function renderSpec(answers) {
  return [
    buildOverview(answers),
    buildFrontend(answers),
    buildBackend(answers),
    buildDatabase(answers),
    buildAuth(answers),
    buildInfra(answers),
    buildQuality(answers),
    buildDirectoryTree(answers),
    buildScaffoldInstructions(answers),
  ].join('\n');
}
